Resources:
    mySecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties: 
        GroupDescription: "CFN Security Group"
        GroupName: "CFN-SG"
        SecurityGroupIngress: 
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 73.44.251.103/32
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress: 
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
        VpcId: vpc-58b62f20
    Ec2Instance: 
      Type: AWS::EC2::Instance
      Properties: 
        ImageId: ami-0dc3c22d98a6a91ff 
        KeyName: citrix-test
        InstanceType: t2.micro
        SecurityGroupIds: 
          - !Ref mySecurityGroup
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties: 
        BucketName: testbucket9234983948
        PublicAccessBlockConfiguration: 
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
Outputs:
  PublicIp:
    Value:
      'Fn::GetAtt':
        - Ec2Instance
        - PublicIp
    Description: Instance's PublicIp Address
